### ISSUE TITLE
Deliverables v1.0

### ISSUE THREAD

**Issue by Cubis-PascalDP** [CubisSolutions/ambari-spark-vora#1]
Overview of deliverables for v1.0:
- [x] Document the way of working in Wiki
- [ ] Setup a deployable Spark-Vora infrastructure ( #10 )
- [ ] Setup a Business Case for Spark ETL, demostrating HANA - SPARK integration ( #22 )
- [ ] Setup a Business Case for predictive analysis and machine learning ( #20)
- [ ] Setup a Business Case for Spark Streaming ( #19 )
- [ ] Setup a Business Case for Graphx ( #21 )
